version: '2.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5000:5000
    env_file:
      - .env-local
    environment:
      - FLASK_ENV=production
    volumes:
      - '.:/usr/src/app'
  app-local:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5000:5000
    env_file:
      - .env-local
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=src:create_app()
      - FLASK_ENV=development
    volumes:
      - '.:/usr/src/app'
    entrypoint: |
      flask run -h 0.0.0.0
  postgres:
    image: postgres
    environment:
    - POSTGRES_USER=local
    - POSTGRES_PASSWORD=local
    - POSTGRES_DB=local
    ports:
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local"]
      interval: 3s
      timeout: 2s
      retries: 3
